releases:
- name: logsearch
  version: latest

jobs:
###############################################################################
#First deploy group - elasticsearch_master, cluster_monitor, queue, maintenance
###############################################################################
- name: elasticsearch_master
  instances: 1
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_master
  persistent_disk_pool: elasticsearch_master
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: false
  update:
    max_in_flight: 1 # Should never update more than one ES master node at a time or cluster will go down

- name: cluster_monitor
  instances: 1
  templates:
  - { release: logsearch, name: queue }
  - { release: logsearch, name: parser }
  - { release: logsearch, name: ingestor_syslog }
  - { release: logsearch, name: elasticsearch }
  - { release: logsearch, name: elasticsearch_config }
  - { release: logsearch, name: curator }
  - { release: logsearch, name: kibana }
  - { release: logsearch, name: nats_to_syslog }
  - { release: logsearch, name: reaper }
  resource_pool: cluster_monitor
  networks:
  - name: default
    static_ips: (( static_ips(2) ))
  persistent_disk_pool: cluster_monitor
  properties:
    kibana:
      port: 5601
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      memory_limit: 30
      wait_for_templates: [shards-and-replicas]
    elasticsearch:
      master_hosts: [127.0.0.1]
      cluster_name: monitor
      node:
        allow_master: true
        allow_data: true
    redis:
      host: 127.0.0.1
      maxmemory: 10
    curator:
      elasticsearch_host: 127.0.0.1
      elasticsearch_port: 9200
      purge_logs:
        retention_period: 7
    reaper:
      elasticsearch_host: 127.0.0.1
      purge_logs:
        disk_threshold: 70
        skip_index: ".kibana,kibana-int,.kibana-vipersleeds, .kibana-onlineservice-skymobile"
    elasticsearch_config:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      templates:
      - shards-and-replicas: "{ \"template\" : \"*\", \"order\" : 99, \"settings\" : { \"number_of_shards\" : 1, \"number_of_replicas\" : 0 } }"
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
    logstash_parser:
      filters:
      - monitor: /var/vcap/packages/logsearch-config/logstash-filters-monitor.conf
    nats_to_syslog:
      nats:
        subject: ">"
        user: nats
        password: nats-password
        port: 4222
        machines: []
      debug: true
      syslog:
        host: 127.0.0.1
        port: 514
    logstash_ingestor:
      syslog:
        port: 514

- name: queue
  instances: 1
  templates:
  - {name: queue, release: logsearch}
  resource_pool: queue
  persistent_disk_pool: queue
  networks:
  - name: default
    static_ips: (( static_ips(3) ))

- name: maintenance
  instances: 1
  templates:
  - {name: elasticsearch_config, release: logsearch}
  - {name: curator, release: logsearch}
  - {name: reaper, release: logsearch}
  resource_pool: maintenance
  networks:
  - name: default
  update:
    serial: true # Block on this job to create deploy group 1

##################################################################
#2nd deploy group - elasticsearch_data, kibana, ingestors, parsers
##################################################################

- name: elasticsearch_data
  instances: 2
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_data
  persistent_disk_pool: elasticsearch_data
  networks:
  - name: default
    static_ips: (( static_ips(16, 17) ))
  properties:
    elasticsearch:
      node:
        allow_master: false
        allow_data: true
  update:
    max_in_flight: 1 # Only update 1 ES data node at a time or risk downtime

- name: kibana
  instances: 1
  templates:
  - {name: kibana, release: logsearch}
  resource_pool: kibana
  networks:
  - name: default
    static_ips: (( static_ips(5) ))

- name: ingestor
  instances: 1
  templates:
  - {name: ingestor_syslog, release: logsearch}
  - {name: ingestor_relp, release: logsearch}
  resource_pool: ingestor
  networks:
  - name: default
    static_ips: (( static_ips(1) ))
  properties:
    logstash_ingestor:
      debug: false
      relp:
        port: ~

- name: parser
  instances: 2
  templates:
  - {name: parser, release: logsearch}
  - {name: elasticsearch, release: logsearch}
  resource_pool: parser
  networks:
  - name: default
  update:
    serial: false # Block to create deploy group 2
    max_in_flight: 4  # Its ok to update multiple parsers at a time

####################################################
#3nd deploy group - ls-router (haproxy), and errands
####################################################

- name: ls-router
  instances: 1
  templates:
  - { name: haproxy, release: logsearch }
  resource_pool: haproxy
  networks:
  - name: default
    default: [gateway, dns]
    static_ips: (( static_ips(9) ))
  properties:
    haproxy:
      syslog_server: (( grab jobs.cluster_monitor.networks.[0].static_ips.[0] ))
      ingestor:
        backend_servers: (( grab jobs.ingestor.networks.[0].static_ips ))
      kibana:
        backend_servers: (( grab jobs.kibana.networks.[0].static_ips ))
      cluster_monitor:
        backend_servers: (( grab jobs.cluster_monitor.networks.[0].static_ips ))

- name: enable_shard_allocation
  instances: 1
  lifecycle: errand
  templates:
  - {name: enable_shard_allocation, release: logsearch}
  resource_pool: errand
  networks:
  - name: default
  properties:
    enable_shard_allocation:
      elasticsearch:
        master_node: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))

- name: smoke-tests
  instances: 1
  resource_pool: errand
  release: logsearch
  templates:
  - {name: smoke-tests, release: logsearch}
  networks:
  - name: default
  lifecycle: errand
  properties:
    smoke_tests:
      syslog_ingestor:
        host: (( grab jobs.ls-router.networks.[0].static_ips.[0] ))
      elasticsearch_master:
        host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))

# Global properties
properties:
  curator:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
  reaper:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
  logstash_parser:
    debug: false
  logstash_ingestor:
    debug: false
  redis:
    host: (( grab jobs.queue.networks.default.static_ips.[0] ))
  elasticsearch:
    master_hosts: (( grab jobs.elasticsearch_master.networks.default.static_ips ))
    cluster_name: logsearch
    exec: ~
  kibana:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
  elasticsearch_config:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
    templates:
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
